[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/test"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
APP_ENV = "production"
APP_DEBUG = "true"
APP_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
LOG_LEVEL = "debug"
DB_CONNECTION = "mysql"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync"
COMPOSER_ALLOW_SUPERUSER = "1"
APP_NAME = "studiu u sicilianu" 