services:
  - type: web
    name: studiu-u-sicilianu
    env: docker
    buildCommand: docker build -t studiu-app .
    startCommand: docker run -p $PORT:80 studiu-app
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: studiu-db
          property: connectionString
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: studiu-db
    databaseName: studiu_sicilianu
    user: studiu_user
    ipAllowList: []
