services:
  - type: web
    name: laravel-vue-app
    env: docker
    dockerfilePath: Dockerfile
    port: 80
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString

databases:
  - name: myapp-db
    ipAllowList: []
