services:
  - type: web
    name: laravel-vue-app
    env: docker
    buildCommand: docker build -t app .
    startCommand: docker run -p 8080:8080 app
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString

databases:
  - name: myapp-db
    ipAllowList: []
